require:
  - rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes


# There are many cases when %r{} is preferable
# due to redability and character escaping
Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: false

Naming/VariableNumber:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
